import React from 'react';
import Head from "next/head";
import HomePage from './HomePage';
import FableLand from './FableLand';
import resume from "../public/kaztaharaedmondsresume.pdf";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { useState } from "react";

function App() {
  const [page, setPage] = React.useState('home');
  const [darkMode, setDarkMode] = useState(true);

  const handlePageChange = (newPage) => {
    setPage(newPage);
  };

  const renderPage = () => {

    if (typeof window !== 'undefined') {
      window.scrollTo(0, 0);
    }
    switch (page) {
      case 'home':
        return <HomePage setPage={handlePageChange}/>;
      case 'FABLELAND':
        return <FableLand setPage={handlePageChange}/>;
      case 'DEADMEAT':
        return <FableLand setPage={handlePageChange}/>;
      case 'FISHERMAN':
        return <FableLand setPage={handlePageChange}/>;
      case 'FPSFUN':
        return <FableLand setPage={handlePageChange} />;
      case 'MASTEROFCASTLES':
        return <FableLand setPage={handlePageChange} />;
      case 'ANIMALROLL':
        return <FableLand setPage={handlePageChange} />;
      default:
        return <HomePage setPage={handlePageChange} />;
    }
  };

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Kaz Tahara-Edmonds Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className="navheader fixed top-0 left-0 right-0 z-10 bg-gray-300 dark:bg-gray-900 px-10 md:px-20 lg:px-40" 
        style={{backgroundColor: darkMode ? 'rgb(20,20,30)' : 'rgb(150,150,150)'}}>
        <nav className="py-10 mb-0 flex justify-between dark:text-white">
          <button className="text-xl navbutton" onClick={() => setPage('home')}>Home</button>
          <ul className="flex items-center">
            <li>
              <BsFillMoonStarsFill
                onClick={() => setDarkMode(!darkMode)}
                className="cursor-pointer text-2xl"
              />
            </li>
            <li>
              <a
                className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8"
                href={resume}
              >
                Resume
              </a>
            </li>
          </ul>
        </nav>
      </header>
      <main className="bg-white dark:bg-gray-900 pt-20 pb-10 px-10 md:px-20 lg:px-40">
      <br></br>
      <br></br>
        {renderPage()}
      </main>
    </div>
  );
}

export default App;